services:
  - type: web
    name: kitakits-chatbot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: kitakits-data
      mountPath: /opt/render/project/src
      sizeGB: 1
